FROM ubuntu:latest
# RUN mkdir /new_dir
# COPY something /new_dir
# 圧縮ファイルをコピーして解凍してくれる
ADD compressed.tar /

# RUN apt-get update && apt-get install -y \
#     curl \
#     nginx \
#     cvs
# 検証中はRUNを複数
# 最後にひとつにまとめる
# RUN apt-get install -y cvs

# CMD ["ls"]
# CMD ["pwd"]
CMD ["/bin/bash"]
