#!/usr/bin/env python3
import sys
import string

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str):
    check_dict = {}
    is_lower = False
    is_upper = False

    for s in S:
        if s in string.ascii_lowercase:
            is_lower = True
        if s in string.ascii_uppercase:
            is_upper = True
        if s in check_dict:
            print(NO)
            return
        else:
            check_dict[s] = 1
    if is_lower and is_upper:
        print(YES)
    else:
        print(NO)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
