#!/usr/bin/env python3
import sys


def solve(N: int):
    print(1)
    if N == 1:
        return
    print(1, 1)

    an = [1, 1]
    for i in range(2, N):
        an_next = []
        for j in range(i + 1):
            if j == 0 or j==i:
                an_next.append(1)
            else:
                an_next.append(an[j-1] + an[j])
        print(" ".join(map(str, an_next)))
        an = an_next

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
