[package]
name = "test-test"
version = "0.1.0"
authors = ["mida-hub <rusuden0106@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
