apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
resources:
  - ../../base
 
# patches:
#   - patch.yaml

replicas:
  - name: nginx-deployment
    count: 3

namespace: prod

namePrefix: pre-

commonLabels:
  app: nginx
  environment: prod

commonAnnotations:
  env: prod**

configMapGenerator:
- name: my-configmap
  behavior: merge
  files:
  - env.properties
