#!/usr/bin/env python3

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n, m = map(int, input().split())

    # 電球がどのスイッチに繋がっているか
    switches = []
    for i in range(m):
        tmp = list(map(int, input().split()))
        switch = [0] * n
        for s in tmp[1:]:
            switch[s-1] = 1
        switches.append(switch)
    #  pi に等しい時に点灯
    pm = list(map(int, input().split()))

    total = 0
    for bit in range(1 << n):
        # 点灯フラグ
        is_result = True
        bits = []
        for i in range(n):
            if (bit & (1 << i)):
                bits.append(1)
            else:
                bits.append(0)

        # 繋がっている電球 × スイッチ ON/OFF
        for i, switch in enumerate(switches):
            count = 0
            for j in range(n):
                count += switch[j] * bits[j]

            # 2で除算した後に pi に等しければ点灯している
            count %= 2
            if pm[i] != count:
                is_result = False
        
        # すべて点灯していればパターンをカウント
        if is_result:
            total += 1
    
    print(total)


if __name__ == '__main__':
    main()
