apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: skaffold-hands-on
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - manifest
