#!/usr/bin/env python3
import sys
import collections

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, s: "List[str]", t: "List[str]"):
    check_dict = {}

    for n in range(N):
        # 性と名が同じ場合はユニークにしてカウントする
        for sti in set([s[n], t[n]]):
            if sti in check_dict:
                check_dict[sti] += 1
            else:
                check_dict[sti] = 1

    for n in range(N):
        if check_dict[s[n]] > 1 and check_dict[t[n]] > 1:
            print(NO)
            return
    
    print(YES)
    return

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = [str()] * (N)  # type: "List[str]"
    t = [str()] * (N)  # type: "List[str]"
    for i in range(N):
        s[i] = next(tokens)
        t[i] = next(tokens)
    solve(N, s, t)

if __name__ == '__main__':
    main()
