[package]
name = "simplecli"
version = "0.1.0"
authors = ["mida-hub <rusuden0106@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
clap = "=3.0.0-beta.2"
thiserror = "1.0.30"
