#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, S: "List[str]"):
    for i in range(N):
        # 右方向
        for j in range(N):
            counter = 0
            if j+6 > N:
                break
            for k in range(6):
                if S[i][j+k] == '#':
                    counter += 1
            if counter >= 4:
                print(YES)
                return
        
        # 下方向
        for j in range(N):
            counter = 0
            if i+6 > N:
                break
            for k in range(6):
                if S[i+k][j] == '#':
                    counter += 1
            if counter >= 4:
                print(YES)
                return

        # 右下斜め方向
        for j in range(N):
            counter = 0
            if i+6 > N or j+6 > N:
                break
            for k in range(6):
                if S[i+k][j+k] == '#':
                    counter += 1
            if counter >= 4:
                print(YES)
                return

        # 左下斜め方向
        for j in range(5, N):
            counter = 0
            if i+6 > N:
                break
            for k in range(6):
                if S[i+k][j-k] == '#':
                    counter += 1
            if counter >= 4:
                print(YES)
                return

    print(NO)
    
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    solve(N, S)

if __name__ == '__main__':
    main()
