#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    n, w = map(int, input().split())
    reservation = {}

    for i in range(n):
        s, t, p = input().split()
        p = int(p)

        if reservation.get(s) is None:
            reservation[s] = p
        else:
            reservation[s] += p
        
        if reservation.get(t) is None:
            reservation[t] = -p
        else:
            reservation[t] -= p
    # print(reservation)

    check = 0
    for i in range(n):
        if reservation.get(str(i)) is not None:
            check += reservation.get(str(i))
        
        if check > w:
            print(NO)
            return
    
    print(YES)

if __name__ == '__main__':
    main()
