apiVersion: v1
kind: Service
metadata:
  labels:
    app: skaffold-hands-on
  name: skaffold-hands-on
spec:
  ports: # 8080ポートを公開
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: skaffold-hands-on # skaffold-hands-onのPODを指定。
