#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str


def solve(S: "List[str]", T: "List[str]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = [next(tokens) for _ in range(3)]  # type: "List[str]"
    T = [next(tokens) for _ in range(3)]  # type: "List[str]"
    solve(S, T)

if __name__ == '__main__':
    main()
