#!/usr/bin/env python3
import sys


def solve(a: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    a = [int(next(tokens)) for _ in range(9 + 1)]  # type: "List[int]"
    solve(a)

if __name__ == '__main__':
    main()
