version: '3'

services:
  web_server:
    build:
      context: .
      dockerfile: ./web_server/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app_service
    restart: always
  app_service:
    build:
      context: .
      dockerfile: ./app_flask/Dockerfile
    expose:
      - 5000
    volumes:
      - './app_flask:/project'
    restart: always
    environment:
      TZ: Asia/Tokyo
