#!/usr/bin/env python3
import enum
import sys


def solve(N: int, A: "List[int]"):
    A = set(sorted(A))

    check_list = [0] * 2001

    for a in A:
        check_list[a] = 1

    for i, a in enumerate(check_list):
        if a == 0:
            print(i)
            return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
