version: "3"

volumes:
    db-data:

services:
    n_pre_school:
        build: "."
        volumes:
            - ".:/workspace"
        ports:
            - "8000:8000"
        environment:
            - "DATABASE_PASSWORD=postgres"
        tty: true
        stdin_open: true
        depends_on:
            - db
        # dbに通信できるようにする
        links:
            - db

    db:
        image: "postgres"
        volumes:
            - "db-data:/var/lib/postgresql/data:z"
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=postgres"
            - "POSTGRES_HOST_AUTH_METHOD=trust"
        ports:
            - 5432:5432
