# Generated by Django 2.2.6 on 2020-12-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_path',
            new_name='FilePath',
        ),
    ]
