# Generated by Django 2.2.6 on 2020-12-13 15:50

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.FileField(storage=config.storage_backends.SchemaStorage(), upload_to='')),
            ],
        ),
    ]
