# Generated by Django 2.2.6 on 2020-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='価格')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
