# Generated by Django 2.2.6 on 2020-11-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='WebDocument',
        ),
    ]
