#!/usr/bin/env python3
import sys

def calc(x, a, b, c):
    total = 0
    while x > 0:
        for _ in range(a):
            total += b
            x -= 1
            if x <= 0:
                return total

        for _ in range(c):
            x -= 1
            if x <= 0:
                return total

def solve(A: int, B: int, C: int, D: int, E: int, F: int, X: int):
    total_takahasi = calc(X, A, B, C)
    total_aoki = calc(X, D, E, F)

    if total_takahasi > total_aoki:
        print("Takahashi")
    elif total_takahasi < total_aoki:
        print("Aoki")
    else:
        print("Draw")
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    D = int(next(tokens))  # type: int
    E = int(next(tokens))  # type: int
    F = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    solve(A, B, C, D, E, F, X)

if __name__ == '__main__':
    main()
