version: '3'

services:
  app:
    container_name: evidence
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    command: sh -c "cd my-project && npm run dev"
    volumes:
      - index.md:/app/my-project/index.md
