version: '3'
services:
  app:
    container_name: evidence
    build: .
    command: sh -c "cd my-project && npm run build"
    volumes:
      - ./pages:/app/my-project/pages
      - ./build:/app/my-project/build
      - ./settings.json:/app/my-project/.evidence/template/evidence.settings.json
