#!/usr/bin/env python3
import sys


def solve(S: str):
    lacked_numbers = list(S)
    # print(lacked_numbers)
    for i in range(10):
        if str(i) not in lacked_numbers:
            print(i)
            return
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
