clf_list:
  Logistic:
    - est__penalty: ['l1', 'l2']
      est__C: [0.1, 1, 10]

  R-forest:
    - est__n_estimators: [10, 20, 30, 100]
      est__max_depth: [3, 5, 7, 20]
      est__max_features: [0.1, 0.3, 0.5]

  G-boost:
    - est__n_estimators: [10, 20, 30, 100]
      est__learning_rate: [0.1, 0.5, 1.]
      est__max_depth: [3, 5, 7, 20]
      est__max_features: [0.1, 0.3, 0.5]

  D-tree:
    - est__criterion: ['gini', 'entropy']
      est__max_depth: [3, 5, 7, 20]
      est__min_samples_split: [2, 4, 6]
      est__min_samples_leaf: [2, 4, 6]

clf_val:
  Logistic:
    - penalty: 'l2'
      C: 1.0

  R-forest:
    - n_estimators: 100
      max_depth: 20
      max_features: 0.5

  G-boost:
    - n_estimators: 30
      learning_rate: 0.1
      max_depth: 20
      max_features: 0.3

  D-tree:
    - criterion: 'gini'
      max_depth: 7
      min_samples_split: 2
      min_samples_leaf: 2