services:
  web:
    init: true
    container_name: nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./build:/opt/build
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
